flaskapp/blog/models.py
import mongoengine as me

class BlogPost(me.Document):
    title = me.StringField(required=True)
    body = me.StringField(required=True)

flaskapp/blog/forms.py
from flask_wtf import FlaskForm
from wtforms import StringField, TextAreaField
from wtforms.validators import DataRequired


class NewBlogPostForm(FlaskForm):
    title = StringField("Title", validators=[DataRequired()])
    body = TextAreaField("Body", validators=[DataRequired()])

flaskapp/blog/__init__.py
from flask import Blueprint

bp = Blueprint("blog", __name__, url_prefix="/blog")

import flaskapp.blog.routes

flaskapp/blog/routes.py
from flask import request, current_app, flash, redirect, url_for, render_template

from flaskapp.blog import bp
from flask_login import login_required

from flaskapp.blog.forms import NewBlogPostForm
from flaskapp.blog import models as MongoModels

@bp.route("/new_post", methods=["POST", "GET"])
@login_required
def new_post():
    form = NewBlogPostForm()
    if request.method == "POST" and form.validate_on_submit():
        blog_post = MongoModels.BlogPost(title=form.title.data, body=form.body.data).save()
        current_app.logger.info("Blog post added: %s", form.title.data)
        flash("Blog Post Added")
        return redirect(url_for("blog.home"))
    return render_template("blog/new_blog_post.html", form=form)

@bp.route("/")
@login_required
def home():
    return render_template("blog/home.html")

flaskapp/templates/blog/home.html
{% extends 'base.html' %}

{% block content %}
<div>
    <ul>
        <li>
            <a href="{{url_for('blog.new_post')}}">New Blog Post!</a>
        </li>
    </ul>
</div>
{% endblock %}

flaskapp/templates/blog/new_blog_post.html
{% extends 'base.html' %}

{% block content %}
    <form method="post">
        {{form.csrf_token}}

        {{form.title.label}} {{form.title()}}
        {{form.body.label}} {{form.body()}}
        <button>Boom</button>
    </form>
{% endblock %}